print("Hello, World!")
print()
print("Soniya. G")
print()
print("All is Well")
print()
print("""
    AI Python Full Stack
    Vetri Technoloty Solutions""")
print()
a=25
b=75
c=10
print(a+b-c)
print()
print("Item \t Qty \t Price")
print("-" *25)
print("APPle \t 2 \t $5")
print("Bread \t 1 \t $2")
print()
for i in range(1, 11):
    print("5\t*\t", i, "\t=\t", 5 * i)
print()
print("  *****  ")
print(" *     * ")
print("*  O O  *")
print("*   ^   *")
print("* \__/ *")
print(" *     * ")
print("  *****  ")
print()
print("***********************")
print("*                     *")
print("*    Hello, Soniya!   *")
print("*                     *")
print("***********************")
print()
print("Html", "Css", "JavaScript", sep="<")
print()
print("Hi", end=" ")
print("Iam Soniya")
print()
name= "Soniya"
age= 27
print(f"My name is {name} and I am {age} years old.")
print()
print(5)
print(4)
print(3)
print(2)
print(1)
print("Go!")
print()
